Repository trifork/cheetah-example-flink, pull requests merged in 2023-11, with the labels that each got.

#55 Feature/update workflow
  .github/workflows/component-test.yml
Labels: e2e-test

#71 Extend ExternalLookupJob with token retrieval
  ExternalLookup/docker-compose.yaml
  ExternalLookup/pom.xml
  ExternalLookup/src/main/java/cheetah/example/externallookup/function/ExternalLookupMapper.java
  ExternalLookup/src/main/java/cheetah/example/externallookup/job/ExternalLookupJob.java
Labels: e2e-test

#66 Implemented cheetah histogram
  Observability/pom.xml
  Observability/src/main/java/cheetah/example/observability/function/CheetahHistogramMapper.java
  Observability/src/main/java/cheetah/example/observability/job/ObservabilityJob.java
Labels: documentation, e2e-test

#75 Bumped lib processing version
  FlinkStates/pom.xml
  MergeTwoStreams/pom.xml
  MultipleSideOutput/pom.xml
  TransformAndStore/pom.xml
  TumblingWindow/pom.xml
Labels: patch-updates, e2e-test

#70 Add SerializationCatchError example
  .github/workflows/component-test.yml
  .github/workflows/maven-build-and-test.yml
  SerializationErrorCatch/.m2/.gitkeep
  SerializationErrorCatch/ComponentTest/.dockerignore
  SerializationErrorCatch/ComponentTest/ComponentTest.cs
  SerializationErrorCatch/ComponentTest/Dockerfile
  SerializationErrorCatch/ComponentTest/Models/BadEvent.cs
  SerializationErrorCatch/ComponentTest/Models/InputEvent.cs
  SerializationErrorCatch/ComponentTest/Models/OutputEvent.cs
  SerializationErrorCatch/ComponentTest/NuGet-CI.Config
  SerializationErrorCatch/ComponentTest/SerializationErrorCatch.ComponentTest.csproj
  SerializationErrorCatch/ComponentTest/SerializationErrorCatch.ComponentTest.sln
  SerializationErrorCatch/ComponentTest/SerializationErrorCatch.ComponentTest.sln.DotSettings.user
  SerializationErrorCatch/ComponentTest/global.json
  SerializationErrorCatch/Dockerfile
  SerializationErrorCatch/README.md
  SerializationErrorCatch/docker-compose.yaml
  SerializationErrorCatch/images/program_dataflow.svg
  SerializationErrorCatch/pom.xml
  SerializationErrorCatch/settings.xml
  SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/FilterAndCountFailedSerializations.java
  SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/function/SerializationErrorCatchMapper.java
  SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/job/SerializationErrorCatchJob.java
  SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/model/InputEvent.java
  SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/model/OutputEvent.java
  SerializationErrorCatch/src/main/java/cheetah/example/serializationerrorcatch/serde/DeserializationSchema.java
  SerializationErrorCatch/src/test/java/cheetah/example/serializationerrorcatch/job/SerializationErrorCatchMapperTest.java
  SerializationErrorCatch/src/test/java/cheetah/example/serializationerrorcatch/model/SerializationErrorCatchInputEventTest.java
  SerializationErrorCatch/src/test/java/cheetah/example/serializationerrorcatch/model/SerializationErrorCatchOutputEventTest.java
Labels: e2e-test

#76 Updated dependency
  FlinkStates/pom.xml
  MergeTwoStreams/pom.xml
  MultipleSideOutput/pom.xml
  TumblingWindow/pom.xml
Labels: e2e-test

#82 Add log4j2.properties file
  ExternalLookup/src/main/resources/log4j2.properties
  FlinkStates/src/main/resources/log4j2.properties
  MergeTwoStreams/src/main/resources/log4j2.properties
  MultipleSideOutput/src/main/resources/log4j2.properties
  Observability/src/main/resources/log4j2.properties
  SerializationErrorCatch/src/main/resources/log4j2.properties
  TransformAndStore/src/main/resources/log4j2.properties
  TumblingWindow/src/main/resources/log4j2.properties
Labels: e2e-test

#99 Workflow cleanup
  .github/actions/component-test/action.yml
  .github/actions/maven-build-and-test/action.yml
  .github/workflows/component-test.yml
  .github/workflows/maven-build-and-test.yml
  .github/workflows/wait-for-all-checks.yml
  ExternalLookup/src/test/java/cheetah/example/externallookup/job/ExternalLookupMapperTest.java
Labels: e2e-test
